from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		w,h=DeskTopSize()
		initUI(self,param,w=w,h=h,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):
		self.createwidget("{'Name': 'mBase', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '0', 'Width': '400', 'ParentsType': '', 'Picture': 'cat.png', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '600', 'Left': '0', 'Tag': '', 'Text': '', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'cbolocation', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '90', 'Width': '190', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '110', 'Tag': '', 'Text': '', 'Help': ''}",'QComboBox','usercontrol',"[]")
		self.createwidget("{'Name': 'btnavailability', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '10', 'Width': '215', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '70', 'Left': '95', 'Tag': '', 'Text': 'QPushButton1', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'seat2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '290', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '65', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'btnnotif', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '140', 'Width': '115', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '145', 'Tag': '', 'Text': 'QPushButton1', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'seat9', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '290', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '265', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '365', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '65', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat5', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '515', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '65', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat8', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '365', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '265', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat7', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '440', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '265', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat4', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '440', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '65', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat6', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '515', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '265', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'seat1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '235', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '65', 'Left': '165', 'Tag': '', 'Text': '', 'Help': ''}",'QFrame','usercontrol',"[]")
		self.createwidget("{'Name': 'lblavail', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '195', 'Width': '180', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '120', 'Tag': '', 'Text': 'Available Seat', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'btnback', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '10', 'Width': '75', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '70', 'Left': '30', 'Tag': '', 'Text': 'QPushButton2', 'Help': ''}",'QPushButton','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
