from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		w,h=DeskTopSize()
		initUI(self,param,w=w,h=h,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):
		self.createwidget("{'Name': 'mBase', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '0', 'Width': '400', 'ParentsType': '', 'Picture': 'Files/settings bg.png', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '600', 'Left': '5', 'Tag': '', 'Text': '', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'btnback', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '20', 'Width': '35', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '25', 'Tag': '', 'Text': '', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '180', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '65', 'Tag': '', 'Text': 'Time', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '170', 'Width': '70', 'ParentsType': '', 'Picture': '', 'ForeColor': '[0.0, 0.0, 0.0, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '125', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel5', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '180', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '220', 'Tag': '', 'Text': 'kWh', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '170', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '270', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate1', 'Var': '', 'Font': 'Arial Rounded MT Bold 10', 'Enable': 'True', 'Top': '95', 'Width': '90', 'ParentsType': '', 'Picture': 'update button.png', 'ForeColor': '[1.0, 1.0, 1.0, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '260', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel8', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '330', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '25', 'Left': '70', 'Tag': '', 'Text': 'Time', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '320', 'Width': '70', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '130', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel10', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '330', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '220', 'Tag': '', 'Text': 'kWh', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '320', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '270', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel12', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '485', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '70', 'Tag': '', 'Text': 'Time', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '475', 'Width': '70', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '130', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel14', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '485', 'Width': '50', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '220', 'Tag': '', 'Text': 'kWh', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '475', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '35', 'Left': '270', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '250', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '[1.0, 1.0, 1.0, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '260', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '400', 'Width': '90', 'ParentsType': '', 'Picture': '', 'ForeColor': '[1.0, 1.0, 1.0, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '260', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'settingsTitle', 'Var': '', 'Font': 'Arial Rounded MT Bold 16', 'Enable': 'True', 'Top': '20', 'Width': '220', 'ParentsType': '', 'Picture': '', 'ForeColor': '[0.9921568627450981, 0.7215686274509804, 0.09411764705882353, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '105', 'Tag': '', 'Text': 'S E T T I N G S', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'line1Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 9', 'Enable': 'True', 'Top': '95', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '65', 'Tag': '', 'Text': 'Line 1', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'limit1Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 8', 'Enable': 'True', 'Top': '130', 'Width': '150', 'ParentsType': '', 'Picture': '', 'ForeColor': '[0.2901960784313726, 0.3411764705882353, 0.34901960784313724, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '65', 'Tag': '', 'Text': 'Set time / kWh limit', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'line2Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 9', 'Enable': 'True', 'Top': '245', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '70', 'Tag': '', 'Text': 'Line 2', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'limit2Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 8', 'Enable': 'True', 'Top': '280', 'Width': '150', 'ParentsType': '', 'Picture': '', 'ForeColor': '[0.2901960784313726, 0.3411764705882353, 0.34901960784313724, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '70', 'Tag': '', 'Text': 'Set time / kWh limit', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'line3Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 9', 'Enable': 'True', 'Top': '400', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '70', 'Tag': '', 'Text': 'Line 3', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'limit3Title', 'Var': '', 'Font': 'Arial Rounded MT Bold 8', 'Enable': 'True', 'Top': '435', 'Width': '150', 'ParentsType': '', 'Picture': '', 'ForeColor': '[0.2901960784313726, 0.3411764705882353, 0.34901960784313724, 1.0]', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '70', 'Tag': '', 'Text': 'Set time / kWh limit', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'settingsBtn', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '545', 'Width': '70', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '170', 'Tag': '', 'Text': '', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'realtimeBtn', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '545', 'Width': '60', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '80', 'Tag': '', 'Text': '', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'historyBtn', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '545', 'Width': '60', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '265', 'Tag': '', 'Text': '', 'Help': ''}",'QPushButton','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
