from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import * 
from wired_module import * 
#	Generated By WiredQT for Python: by Rocky Nuarin, 2021 Phils
class Handler(QtWidgets.QWidget,usercontrol):
	def __init__(self, *param):    
		super(Handler, self).__init__(None)
		w,h=DeskTopSize()
		initUI(self,param,w=w,h=h,title="WiredQTv5.0",controlbox=True,startpos=(0,30),timeoutdestroy=-1)
		self.GTKForms()
		self.timer=QtCore.QTimer()
		self.timer.timeout.connect(self.loop)
		self.timer.start(10)       

		self.sch=Scheduler(5000)#500 ms
		self.sch.Start()
		

	def createwidget(self,prop,control,parent,event=[]):
		createWidget(self,prop,control,parent,event)         
	def GTKForms(self):
		self.createwidget("{'Name': 'mBase', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '0', 'Width': '400', 'ParentsType': '', 'Picture': 'Files/cat.png', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '600', 'Left': '0', 'Tag': '', 'Text': '', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'btnback', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '530', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '15', 'Tag': '', 'Text': '<<', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '50', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'Time 1', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '50', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel5', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '95', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'KW 1', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '95', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate1', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '85', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '265', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel8', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '180', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'KW 2', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '180', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel10', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '225', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'KW 2', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '225', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel12', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '285', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'KW 3', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txttime3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '285', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'QLabel14', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '330', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '45', 'Tag': '', 'Text': 'KW 3', 'Help': ''}",'QLabel','usercontrol',"[]")
		self.createwidget("{'Name': 'txtkw3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '330', 'Width': '100', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '30', 'Left': '155', 'Tag': '', 'Text': '0', 'Help': ''}",'QLineEdit','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate2', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '215', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '270', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
		self.createwidget("{'Name': 'btnupdate3', 'Var': '', 'Font': '', 'Enable': 'True', 'Top': '320', 'Width': '80', 'ParentsType': '', 'Picture': '', 'ForeColor': '(0,0,0,1)', 'Visible': 'True', 'BackColor': '(1,1,1,0.25)', 'Events': [], 'Height': '40', 'Left': '270', 'Tag': '', 'Text': 'Update', 'Help': ''}",'QPushButton','usercontrol',"[]")
	def Widget(self):
		return self    
	def loop(self):
		if self.form_load==False:
			self.form_load=True
		if self.sch.Event():#timer routine
			#code here
			if self.timeoutdestroy!=-1:
				self.timeoutdestroy-=1
				if self.timeoutdestroy==0:
					pass#self.unload(None)
			self.sch.Start()#restart scheduler      
		
	def connect(self,ev,evusr):
		self.wiredevents.update({ev:evusr})     
	def activeXcreated(self,*args):
		pass    
	def eventFilter(self, obj, event):
		return super(Handler, self).eventFilter(obj, event)
	
if __name__ == '__main__':
	import sys
	app = QtWidgets.QApplication(sys.argv)
	w = Handler()
	w.show()
	sys.exit(app.exec_())
