package b4a.esalbaapp;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class frmcontrol extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    private static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new BA(_ba, this, htSubs, "b4a.esalbaapp.frmcontrol");
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            
        }
        if (BA.isShellModeRuntimeCheck(ba)) 
			   this.getClass().getMethod("_class_globals", b4a.esalbaapp.frmcontrol.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 public anywheresoftware.b4a.keywords.Common __c = null;
public String _meventname = "";
public Object _mcallback = null;
public anywheresoftware.b4a.objects.PanelWrapper _mbase = null;
public int _defaultcolorconstant = 0;
public anywheresoftware.b4a.objects.ImageViewWrapper _bkgimage = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel1 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _btnback = null;
public anywheresoftware.b4a.objects.ButtonWrapper _on1 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _on3 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _on2 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _off1 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _off2 = null;
public anywheresoftware.b4a.objects.ButtonWrapper _off3 = null;
public anywheresoftware.b4a.objects.LabelWrapper _realtimetitle = null;
public anywheresoftware.b4a.keywords.constants.TypefaceWrapper _sourcesanspro = null;
public anywheresoftware.b4a.objects.LabelWrapper _line2title = null;
public anywheresoftware.b4a.objects.LabelWrapper _line1title = null;
public anywheresoftware.b4a.objects.LabelWrapper _line3title = null;
public anywheresoftware.b4a.objects.LabelWrapper _kwh1 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel18 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel17 = null;
public anywheresoftware.b4a.objects.LabelWrapper _power1 = null;
public anywheresoftware.b4a.objects.LabelWrapper _voltage1 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel20 = null;
public anywheresoftware.b4a.objects.LabelWrapper _current1 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel22 = null;
public anywheresoftware.b4a.objects.LabelWrapper _cost1 = null;
public anywheresoftware.b4a.objects.LabelWrapper _kwh2 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel25 = null;
public anywheresoftware.b4a.objects.LabelWrapper _current2 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel27 = null;
public anywheresoftware.b4a.objects.LabelWrapper _voltage2 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel29 = null;
public anywheresoftware.b4a.objects.LabelWrapper _power2 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel31 = null;
public anywheresoftware.b4a.objects.LabelWrapper _cost2 = null;
public anywheresoftware.b4a.objects.LabelWrapper _kwh3 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel34 = null;
public anywheresoftware.b4a.objects.LabelWrapper _current3 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel36 = null;
public anywheresoftware.b4a.objects.LabelWrapper _voltage3 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel38 = null;
public anywheresoftware.b4a.objects.LabelWrapper _power3 = null;
public anywheresoftware.b4a.objects.LabelWrapper _qlabel40 = null;
public anywheresoftware.b4a.objects.LabelWrapper _cost3 = null;
public b4a.example.dateutils _dateutils = null;
public b4a.esalbaapp.main _main = null;
public b4a.esalbaapp.vb6 _vb6 = null;
public b4a.esalbaapp.starter _starter = null;
public b4a.esalbaapp.b4xcollections _b4xcollections = null;
public b4a.esalbaapp.xuiviewsutils _xuiviewsutils = null;
public String  _addtoparent(anywheresoftware.b4a.objects.ActivityWrapper _parent,int _left,int _top,int _width,int _height) throws Exception{
 //BA.debugLineNum = 58;BA.debugLine="Public Sub AddToParent(Parent As Activity, Left As";
 //BA.debugLineNum = 59;BA.debugLine="mBase.Initialize(\"mBase\")";
_mbase.Initialize(ba,"mBase");
 //BA.debugLineNum = 60;BA.debugLine="Parent.AddView(mBase, Left, Top, Width, Height)";
_parent.AddView((android.view.View)(_mbase.getObject()),_left,_top,_width,_height);
 //BA.debugLineNum = 61;BA.debugLine="GTKForms";
_gtkforms();
 //BA.debugLineNum = 62;BA.debugLine="End Sub";
return "";
}
public String  _btnavailability_click() throws Exception{
 //BA.debugLineNum = 399;BA.debugLine="Sub btnavailability_click()";
 //BA.debugLineNum = 400;BA.debugLine="End Sub";
return "";
}
public String  _btnback_click() throws Exception{
b4a.esalbaapp.frmmain _frmmain1 = null;
 //BA.debugLineNum = 392;BA.debugLine="Sub btnback_click()";
 //BA.debugLineNum = 393;BA.debugLine="Dim frmmain1 As frmmain=Starter.frmmain1";
_frmmain1 = (b4a.esalbaapp.frmmain)(_starter._frmmain1 /*Object*/ );
 //BA.debugLineNum = 394;BA.debugLine="frmmain1.Visible=True";
_frmmain1._setvisible /*boolean*/ (__c.True);
 //BA.debugLineNum = 395;BA.debugLine="setVisible(False)";
_setvisible(__c.False);
 //BA.debugLineNum = 396;BA.debugLine="End Sub";
return "";
}
public String  _btnnotif_click() throws Exception{
 //BA.debugLineNum = 403;BA.debugLine="Sub btnnotif_click()";
 //BA.debugLineNum = 405;BA.debugLine="End Sub";
return "";
}
public String  _cbolocation_itemclick(int _position,Object _value) throws Exception{
 //BA.debugLineNum = 397;BA.debugLine="Sub cbolocation_ItemClick (Position As Int, Value";
 //BA.debugLineNum = 398;BA.debugLine="End Sub";
return "";
}
public String  _class_globals() throws Exception{
 //BA.debugLineNum = 6;BA.debugLine="Sub Class_Globals";
 //BA.debugLineNum = 7;BA.debugLine="Private mEventName As String 'ignore";
_meventname = "";
 //BA.debugLineNum = 8;BA.debugLine="Private mCallBack As Object 'ignore";
_mcallback = new Object();
 //BA.debugLineNum = 9;BA.debugLine="Private mBase As Panel";
_mbase = new anywheresoftware.b4a.objects.PanelWrapper();
 //BA.debugLineNum = 10;BA.debugLine="Private Const DefaultColorConstant As Int = -9848";
_defaultcolorconstant = (int) (-984833);
 //BA.debugLineNum = 11;BA.debugLine="Dim bkgimage As ImageView";
_bkgimage = new anywheresoftware.b4a.objects.ImageViewWrapper();
 //BA.debugLineNum = 12;BA.debugLine="Dim QLabel1 As Label";
_qlabel1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 13;BA.debugLine="Dim btnback As Button";
_btnback = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 14;BA.debugLine="Dim on1 As Button";
_on1 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 15;BA.debugLine="Dim on3 As Button";
_on3 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 16;BA.debugLine="Dim on2 As Button";
_on2 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 17;BA.debugLine="Dim off1 As Button";
_off1 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 18;BA.debugLine="Dim off2 As Button";
_off2 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 19;BA.debugLine="Dim off3 As Button";
_off3 = new anywheresoftware.b4a.objects.ButtonWrapper();
 //BA.debugLineNum = 20;BA.debugLine="Dim realtimeTitle As Label";
_realtimetitle = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 22;BA.debugLine="Dim sourcesanspro As Typeface";
_sourcesanspro = new anywheresoftware.b4a.keywords.constants.TypefaceWrapper();
 //BA.debugLineNum = 23;BA.debugLine="sourcesanspro = Typeface.LoadFromAssets(\"SourceSa";
_sourcesanspro = (anywheresoftware.b4a.keywords.constants.TypefaceWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.keywords.constants.TypefaceWrapper(), (android.graphics.Typeface)(__c.Typeface.LoadFromAssets("SourceSansPro-Regular.ttf")));
 //BA.debugLineNum = 25;BA.debugLine="Dim line2Title As Label";
_line2title = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 26;BA.debugLine="Dim line1Title As Label";
_line1title = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 27;BA.debugLine="Dim line3Title As Label";
_line3title = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 28;BA.debugLine="Dim kwh1 As Label";
_kwh1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 29;BA.debugLine="Dim QLabel18 As Label";
_qlabel18 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 30;BA.debugLine="Dim QLabel17 As Label";
_qlabel17 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 31;BA.debugLine="Dim power1 As Label";
_power1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 32;BA.debugLine="Dim voltage1 As Label";
_voltage1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 33;BA.debugLine="Dim QLabel20 As Label";
_qlabel20 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 34;BA.debugLine="Dim current1 As Label";
_current1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 35;BA.debugLine="Dim QLabel22 As Label";
_qlabel22 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 36;BA.debugLine="Dim cost1 As Label";
_cost1 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 37;BA.debugLine="Dim kwh2 As Label";
_kwh2 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 38;BA.debugLine="Dim QLabel25 As Label";
_qlabel25 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 39;BA.debugLine="Dim current2 As Label";
_current2 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 40;BA.debugLine="Dim QLabel27 As Label";
_qlabel27 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 41;BA.debugLine="Dim voltage2 As Label";
_voltage2 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 42;BA.debugLine="Dim QLabel29 As Label";
_qlabel29 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 43;BA.debugLine="Dim power2 As Label";
_power2 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 44;BA.debugLine="Dim QLabel31 As Label";
_qlabel31 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 45;BA.debugLine="Dim cost2 As Label";
_cost2 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 46;BA.debugLine="Dim kwh3 As Label";
_kwh3 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 47;BA.debugLine="Dim QLabel34 As Label";
_qlabel34 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 48;BA.debugLine="Dim current3 As Label";
_current3 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 49;BA.debugLine="Dim QLabel36 As Label";
_qlabel36 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 50;BA.debugLine="Dim voltage3 As Label";
_voltage3 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 51;BA.debugLine="Dim QLabel38 As Label";
_qlabel38 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 52;BA.debugLine="Dim power3 As Label";
_power3 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 53;BA.debugLine="Dim QLabel40 As Label";
_qlabel40 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 54;BA.debugLine="Dim cost3 As Label";
_cost3 = new anywheresoftware.b4a.objects.LabelWrapper();
 //BA.debugLineNum = 55;BA.debugLine="End Sub";
return "";
}
public String  _designercreateview(anywheresoftware.b4a.objects.PanelWrapper _base,anywheresoftware.b4a.objects.LabelWrapper _lbl,anywheresoftware.b4a.objects.collections.Map _props) throws Exception{
 //BA.debugLineNum = 108;BA.debugLine="Public Sub DesignerCreateView (Base As Panel, Lbl";
 //BA.debugLineNum = 109;BA.debugLine="mBase = Base";
_mbase = _base;
 //BA.debugLineNum = 110;BA.debugLine="GTKForms";
_gtkforms();
 //BA.debugLineNum = 111;BA.debugLine="End Sub";
return "";
}
public anywheresoftware.b4a.objects.PanelWrapper  _getbase() throws Exception{
 //BA.debugLineNum = 454;BA.debugLine="Public Sub GetBase As Panel";
 //BA.debugLineNum = 455;BA.debugLine="Return mBase";
if (true) return _mbase;
 //BA.debugLineNum = 456;BA.debugLine="End Sub";
return null;
}
public boolean  _getvisible() throws Exception{
 //BA.debugLineNum = 444;BA.debugLine="Public Sub getVisible() As Boolean";
 //BA.debugLineNum = 445;BA.debugLine="Return mBase.Visible";
if (true) return _mbase.getVisible();
 //BA.debugLineNum = 446;BA.debugLine="End Sub";
return false;
}
public String  _gtkforms() throws Exception{
 //BA.debugLineNum = 112;BA.debugLine="Public Sub GTKForms";
 //BA.debugLineNum = 113;BA.debugLine="mBase.Color=0x000000'transparent background";
_mbase.setColor(((int)0x000000));
 //BA.debugLineNum = 114;BA.debugLine="mBase.Width=100%x";
_mbase.setWidth(__c.PerXToCurrent((float) (100),ba));
 //BA.debugLineNum = 115;BA.debugLine="mBase.height=100%y";
_mbase.setHeight(__c.PerYToCurrent((float) (100),ba));
 //BA.debugLineNum = 117;BA.debugLine="mBase.AddView(bkgimage,0.00 * mBase.Width,0.00 *";
_mbase.AddView((android.view.View)(_bkgimage.getObject()),(int) (0.00*_mbase.getWidth()),(int) (0.00*_mbase.getHeight()),(int) (1.00*_mbase.getWidth()),(int) (1.00*_mbase.getHeight()));
 //BA.debugLineNum = 118;BA.debugLine="bkgimage.Bitmap = LoadBitmapResize(File.DirAssets";
_bkgimage.setBitmap((android.graphics.Bitmap)(__c.LoadBitmapResize(__c.File.getDirAssets(),"settings bg.png",_bkgimage.getWidth(),_bkgimage.getHeight(),__c.False).getObject()));
 //BA.debugLineNum = 120;BA.debugLine="QLabel1.Color =  0x00ffffff";
_qlabel1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 121;BA.debugLine="QLabel1.TextColor = 0xff000000";
_qlabel1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 122;BA.debugLine="QLabel1.Gravity = Gravity.Left";
_qlabel1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 124;BA.debugLine="Starter.image(on1,\"update button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_on1.getObject())),"update button.png");
 //BA.debugLineNum = 125;BA.debugLine="Starter.image(on2,\"update button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_on2.getObject())),"update button.png");
 //BA.debugLineNum = 126;BA.debugLine="Starter.image(on3,\"update button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_on3.getObject())),"update button.png");
 //BA.debugLineNum = 127;BA.debugLine="Starter.image(off1,\"off button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_off1.getObject())),"off button.png");
 //BA.debugLineNum = 128;BA.debugLine="Starter.image(off2,\"off button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_off2.getObject())),"off button.png");
 //BA.debugLineNum = 129;BA.debugLine="Starter.image(off3,\"off button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_off3.getObject())),"off button.png");
 //BA.debugLineNum = 130;BA.debugLine="Starter.image(btnback,\"back button.png\")";
_starter._image /*String*/ ((anywheresoftware.b4a.objects.ConcreteViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.ConcreteViewWrapper(), (android.view.View)(_btnback.getObject())),"back button.png");
 //BA.debugLineNum = 132;BA.debugLine="btnback.Text = \"\"";
_btnback.setText(BA.ObjectToCharSequence(""));
 //BA.debugLineNum = 133;BA.debugLine="btnback.TextColor = 0xff000000";
_btnback.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 135;BA.debugLine="realtimeTitle.Color =  0x00ffffff";
_realtimetitle.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 136;BA.debugLine="realtimeTitle.TextColor = 0xfffdb818";
_realtimetitle.setTextColor(((int)0xfffdb818));
 //BA.debugLineNum = 137;BA.debugLine="realtimeTitle.Gravity = Gravity.Left";
_realtimetitle.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 138;BA.debugLine="realtimeTitle.Text = \"R E A L T I M E\"";
_realtimetitle.setText(BA.ObjectToCharSequence("R E A L T I M E"));
 //BA.debugLineNum = 139;BA.debugLine="realtimeTitle.TextSize = 28";
_realtimetitle.setTextSize((float) (28));
 //BA.debugLineNum = 140;BA.debugLine="realtimeTitle.Typeface = sourcesanspro.DEFAULT_BO";
_realtimetitle.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 142;BA.debugLine="mBase.AddView(realtimeTitle,0.24 * mBase.Width,0.";
_mbase.AddView((android.view.View)(_realtimetitle.getObject()),(int) (0.24*_mbase.getWidth()),(int) (0.03*_mbase.getHeight()),(int) (0.55*_mbase.getWidth()),(int) (0.05*_mbase.getHeight()));
 //BA.debugLineNum = 143;BA.debugLine="on1.Text = \"O N\"";
_on1.setText(BA.ObjectToCharSequence("O N"));
 //BA.debugLineNum = 144;BA.debugLine="on3.Text = \"O N\"";
_on3.setText(BA.ObjectToCharSequence("O N"));
 //BA.debugLineNum = 145;BA.debugLine="on2.Text = \"O N\"";
_on2.setText(BA.ObjectToCharSequence("O N"));
 //BA.debugLineNum = 146;BA.debugLine="on1.Typeface = sourcesanspro.DEFAULT_BOLD";
_on1.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 147;BA.debugLine="on2.Typeface = sourcesanspro.DEFAULT_BOLD";
_on2.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 148;BA.debugLine="on3.Typeface = sourcesanspro.DEFAULT_BOLD";
_on3.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 149;BA.debugLine="off1.Text = \"O F F\"";
_off1.setText(BA.ObjectToCharSequence("O F F"));
 //BA.debugLineNum = 150;BA.debugLine="off2.Text = \"O F F\"";
_off2.setText(BA.ObjectToCharSequence("O F F"));
 //BA.debugLineNum = 151;BA.debugLine="off3.Text = \"O F F\"";
_off3.setText(BA.ObjectToCharSequence("O F F"));
 //BA.debugLineNum = 152;BA.debugLine="off1.Typeface = sourcesanspro.DEFAULT_BOLD";
_off1.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 153;BA.debugLine="off2.Typeface = sourcesanspro.DEFAULT_BOLD";
_off2.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 154;BA.debugLine="off3.Typeface = sourcesanspro.DEFAULT_BOLD";
_off3.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 156;BA.debugLine="on1.TextColor = 0xffffffff";
_on1.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 157;BA.debugLine="on3.TextColor = 0xffffffff";
_on3.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 158;BA.debugLine="on2.TextColor = 0xffffffff";
_on2.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 159;BA.debugLine="off1.TextColor = 0xffffffff";
_off1.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 160;BA.debugLine="off2.TextColor = 0xffffffff";
_off2.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 161;BA.debugLine="off3.TextColor = 0xffffffff";
_off3.setTextColor(((int)0xffffffff));
 //BA.debugLineNum = 163;BA.debugLine="line2Title.Color =  0x00ffffff";
_line2title.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 164;BA.debugLine="line2Title.TextColor = 0xff000000";
_line2title.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 165;BA.debugLine="line2Title.Gravity = Gravity.Left";
_line2title.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 166;BA.debugLine="line2Title.Text = \"Line 2\"";
_line2title.setText(BA.ObjectToCharSequence("Line 2"));
 //BA.debugLineNum = 167;BA.debugLine="line2Title.TextSize = 16";
_line2title.setTextSize((float) (16));
 //BA.debugLineNum = 168;BA.debugLine="line2Title.Typeface = sourcesanspro.DEFAULT_BOLD";
_line2title.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 170;BA.debugLine="line1Title.Color =  0x00ffffff";
_line1title.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 171;BA.debugLine="line1Title.TextColor = 0xff000000";
_line1title.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 172;BA.debugLine="line1Title.Gravity = Gravity.Left";
_line1title.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 173;BA.debugLine="line1Title.Text = \"Line 1\"";
_line1title.setText(BA.ObjectToCharSequence("Line 1"));
 //BA.debugLineNum = 174;BA.debugLine="line1Title.TextSize = 16";
_line1title.setTextSize((float) (16));
 //BA.debugLineNum = 175;BA.debugLine="line1Title.Typeface = sourcesanspro.DEFAULT_BOLD";
_line1title.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 177;BA.debugLine="line3Title.Color =  0x00ffffff";
_line3title.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 178;BA.debugLine="line3Title.TextColor = 0xff000000";
_line3title.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 179;BA.debugLine="line3Title.Gravity = Gravity.Left";
_line3title.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 180;BA.debugLine="line3Title.Text = \"Line 3\"";
_line3title.setText(BA.ObjectToCharSequence("Line 3"));
 //BA.debugLineNum = 181;BA.debugLine="line3Title.TextSize = 16";
_line3title.setTextSize((float) (16));
 //BA.debugLineNum = 182;BA.debugLine="line3Title.Typeface = sourcesanspro.DEFAULT_BOLD";
_line3title.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 185;BA.debugLine="kwh1.Color =  0x00ffffff";
_kwh1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 186;BA.debugLine="kwh1.TextColor = 0xff000000";
_kwh1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 187;BA.debugLine="kwh1.Gravity = Gravity.Left";
_kwh1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 188;BA.debugLine="kwh1.Text = \"kWh\"";
_kwh1.setText(BA.ObjectToCharSequence("kWh"));
 //BA.debugLineNum = 189;BA.debugLine="kwh1.TextSize = 14";
_kwh1.setTextSize((float) (14));
 //BA.debugLineNum = 190;BA.debugLine="kwh1.Typeface = sourcesanspro.DEFAULT_BOLD";
_kwh1.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 191;BA.debugLine="mBase.AddView(kwh1,0.14 * mBase.Width,0.20 * mBas";
_mbase.AddView((android.view.View)(_kwh1.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.20*_mbase.getHeight()),(int) (0.33*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 193;BA.debugLine="QLabel18.Color =  0x00ffffff";
_qlabel18.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 194;BA.debugLine="QLabel18.TextColor = 0xff000000";
_qlabel18.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 195;BA.debugLine="QLabel18.Gravity = Gravity.Left";
_qlabel18.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 196;BA.debugLine="QLabel18.Text = \"Power\"";
_qlabel18.setText(BA.ObjectToCharSequence("Power"));
 //BA.debugLineNum = 197;BA.debugLine="QLabel18.TextSize = 12";
_qlabel18.setTextSize((float) (12));
 //BA.debugLineNum = 198;BA.debugLine="QLabel18.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel18.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 199;BA.debugLine="mBase.AddView(QLabel18,0.51 * mBase.Width,0.25 *";
_mbase.AddView((android.view.View)(_qlabel18.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.25*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 201;BA.debugLine="QLabel17.Color =  0x00ffffff";
_qlabel17.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 202;BA.debugLine="QLabel17.TextColor = 0xff000000";
_qlabel17.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 203;BA.debugLine="QLabel17.Gravity = Gravity.Left";
_qlabel17.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 204;BA.debugLine="QLabel17.Text = \"Voltage\"";
_qlabel17.setText(BA.ObjectToCharSequence("Voltage"));
 //BA.debugLineNum = 205;BA.debugLine="QLabel17.TextSize = 12";
_qlabel17.setTextSize((float) (12));
 //BA.debugLineNum = 206;BA.debugLine="QLabel17.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel17.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 207;BA.debugLine="mBase.AddView(QLabel17,0.14 * mBase.Width,0.29 *";
_mbase.AddView((android.view.View)(_qlabel17.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.29*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 209;BA.debugLine="power1.Color =  0x00ffffff";
_power1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 210;BA.debugLine="power1.TextColor = 0xff000000";
_power1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 211;BA.debugLine="power1.Gravity = Gravity.Left";
_power1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 212;BA.debugLine="power1.Text = \"Power 1\"";
_power1.setText(BA.ObjectToCharSequence("Power 1"));
 //BA.debugLineNum = 213;BA.debugLine="mBase.AddView(power1,0.69 * mBase.Width,0.25 * mB";
_mbase.AddView((android.view.View)(_power1.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.25*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 215;BA.debugLine="voltage1.Color =  0x00ffffff";
_voltage1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 216;BA.debugLine="voltage1.TextColor = 0xff000000";
_voltage1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 217;BA.debugLine="voltage1.Gravity = Gravity.Left";
_voltage1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 218;BA.debugLine="voltage1.Text = \"Voltage 1\"";
_voltage1.setText(BA.ObjectToCharSequence("Voltage 1"));
 //BA.debugLineNum = 219;BA.debugLine="mBase.AddView(voltage1,0.31 * mBase.Width,0.29 *";
_mbase.AddView((android.view.View)(_voltage1.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.29*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 221;BA.debugLine="QLabel20.Color =  0x00ffffff";
_qlabel20.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 222;BA.debugLine="QLabel20.TextColor = 0xff000000";
_qlabel20.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 223;BA.debugLine="QLabel20.Gravity = Gravity.Left";
_qlabel20.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 224;BA.debugLine="QLabel20.Text = \"Current\"";
_qlabel20.setText(BA.ObjectToCharSequence("Current"));
 //BA.debugLineNum = 225;BA.debugLine="QLabel20.TextSize = 12";
_qlabel20.setTextSize((float) (12));
 //BA.debugLineNum = 226;BA.debugLine="QLabel20.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel20.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 227;BA.debugLine="mBase.AddView(QLabel20,0.14 * mBase.Width,0.25 *";
_mbase.AddView((android.view.View)(_qlabel20.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.25*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 229;BA.debugLine="current1.Color =  0x00ffffff";
_current1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 230;BA.debugLine="current1.TextColor = 0xff000000";
_current1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 231;BA.debugLine="current1.Gravity = Gravity.Left";
_current1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 232;BA.debugLine="current1.Text = \"Current 1\"";
_current1.setText(BA.ObjectToCharSequence("Current 1"));
 //BA.debugLineNum = 233;BA.debugLine="mBase.AddView(current1,0.31 * mBase.Width,0.25 *";
_mbase.AddView((android.view.View)(_current1.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.25*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 235;BA.debugLine="QLabel22.Color =  0x00ffffff";
_qlabel22.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 236;BA.debugLine="QLabel22.TextColor = 0xff000000";
_qlabel22.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 237;BA.debugLine="QLabel22.Gravity = Gravity.Left";
_qlabel22.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 238;BA.debugLine="QLabel22.Text = \"Cost(Php)\"";
_qlabel22.setText(BA.ObjectToCharSequence("Cost(Php)"));
 //BA.debugLineNum = 239;BA.debugLine="QLabel22.TextSize = 12";
_qlabel22.setTextSize((float) (12));
 //BA.debugLineNum = 240;BA.debugLine="QLabel22.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel22.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 241;BA.debugLine="mBase.AddView(QLabel22,0.51 * mBase.Width,0.29 *";
_mbase.AddView((android.view.View)(_qlabel22.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.29*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 243;BA.debugLine="cost1.Color =  0x00ffffff";
_cost1.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 244;BA.debugLine="cost1.TextColor = 0xff000000";
_cost1.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 245;BA.debugLine="cost1.Gravity = Gravity.Left";
_cost1.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 246;BA.debugLine="cost1.Text = \"Cost 1\"";
_cost1.setText(BA.ObjectToCharSequence("Cost 1"));
 //BA.debugLineNum = 247;BA.debugLine="mBase.AddView(cost1,0.69 * mBase.Width,0.29 * mBa";
_mbase.AddView((android.view.View)(_cost1.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.29*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 250;BA.debugLine="kwh2.Color =  0x00ffffff";
_kwh2.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 251;BA.debugLine="kwh2.TextColor = 0xff000000";
_kwh2.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 252;BA.debugLine="kwh2.Gravity = Gravity.Left";
_kwh2.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 253;BA.debugLine="kwh2.Text = \"kWh\"";
_kwh2.setText(BA.ObjectToCharSequence("kWh"));
 //BA.debugLineNum = 254;BA.debugLine="kwh2.TextSize = 14";
_kwh2.setTextSize((float) (14));
 //BA.debugLineNum = 255;BA.debugLine="kwh2.Typeface = sourcesanspro.DEFAULT_BOLD";
_kwh2.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 256;BA.debugLine="mBase.AddView(kwh2,0.14 * mBase.Width,0.48 * mBas";
_mbase.AddView((android.view.View)(_kwh2.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.48*_mbase.getHeight()),(int) (0.33*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 258;BA.debugLine="QLabel25.Color =  0x00ffffff";
_qlabel25.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 259;BA.debugLine="QLabel25.TextColor = 0xff000000";
_qlabel25.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 260;BA.debugLine="QLabel25.Gravity = Gravity.Left";
_qlabel25.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 261;BA.debugLine="QLabel25.Text = \"Current\"";
_qlabel25.setText(BA.ObjectToCharSequence("Current"));
 //BA.debugLineNum = 262;BA.debugLine="QLabel25.TextSize = 12";
_qlabel25.setTextSize((float) (12));
 //BA.debugLineNum = 263;BA.debugLine="QLabel25.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel25.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 264;BA.debugLine="mBase.AddView(QLabel25,0.14 * mBase.Width,0.53 *";
_mbase.AddView((android.view.View)(_qlabel25.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.53*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 266;BA.debugLine="current2.Color =  0x00ffffff";
_current2.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 267;BA.debugLine="current2.TextColor = 0xff000000";
_current2.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 268;BA.debugLine="current2.Gravity = Gravity.Left";
_current2.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 269;BA.debugLine="current2.Text = \"Current 2\"";
_current2.setText(BA.ObjectToCharSequence("Current 2"));
 //BA.debugLineNum = 270;BA.debugLine="mBase.AddView(current2,0.31 * mBase.Width,0.53 *";
_mbase.AddView((android.view.View)(_current2.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.53*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 272;BA.debugLine="QLabel27.Color =  0x00ffffff";
_qlabel27.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 273;BA.debugLine="QLabel27.TextColor = 0xff000000";
_qlabel27.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 274;BA.debugLine="QLabel27.Gravity = Gravity.Left";
_qlabel27.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 275;BA.debugLine="QLabel27.Text = \"Voltage\"";
_qlabel27.setText(BA.ObjectToCharSequence("Voltage"));
 //BA.debugLineNum = 276;BA.debugLine="QLabel27.TextSize = 12";
_qlabel27.setTextSize((float) (12));
 //BA.debugLineNum = 277;BA.debugLine="QLabel27.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel27.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 278;BA.debugLine="mBase.AddView(QLabel27,0.14 * mBase.Width,0.57 *";
_mbase.AddView((android.view.View)(_qlabel27.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.57*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 280;BA.debugLine="voltage2.Color =  0x00ffffff";
_voltage2.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 281;BA.debugLine="voltage2.TextColor = 0xff000000";
_voltage2.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 282;BA.debugLine="voltage2.Gravity = Gravity.Left";
_voltage2.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 283;BA.debugLine="voltage2.Text = \"Voltage 2\"";
_voltage2.setText(BA.ObjectToCharSequence("Voltage 2"));
 //BA.debugLineNum = 284;BA.debugLine="mBase.AddView(voltage2,0.31 * mBase.Width,0.57 *";
_mbase.AddView((android.view.View)(_voltage2.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.57*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 286;BA.debugLine="QLabel29.Color =  0x00ffffff";
_qlabel29.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 287;BA.debugLine="QLabel29.TextColor = 0xff000000";
_qlabel29.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 288;BA.debugLine="QLabel29.Gravity = Gravity.Left";
_qlabel29.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 289;BA.debugLine="QLabel29.Text = \"Power\"";
_qlabel29.setText(BA.ObjectToCharSequence("Power"));
 //BA.debugLineNum = 290;BA.debugLine="QLabel29.TextSize = 12";
_qlabel29.setTextSize((float) (12));
 //BA.debugLineNum = 291;BA.debugLine="QLabel29.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel29.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 292;BA.debugLine="mBase.AddView(QLabel29,0.51 * mBase.Width,0.53 *";
_mbase.AddView((android.view.View)(_qlabel29.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.53*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 294;BA.debugLine="power2.Color =  0x00ffffff";
_power2.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 295;BA.debugLine="power2.TextColor = 0xff000000";
_power2.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 296;BA.debugLine="power2.Gravity = Gravity.Left";
_power2.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 297;BA.debugLine="power2.Text = \"Power 2\"";
_power2.setText(BA.ObjectToCharSequence("Power 2"));
 //BA.debugLineNum = 298;BA.debugLine="mBase.AddView(power2,0.69 * mBase.Width,0.53 * mB";
_mbase.AddView((android.view.View)(_power2.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.53*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 300;BA.debugLine="QLabel31.Color =  0x00ffffff";
_qlabel31.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 301;BA.debugLine="QLabel31.TextColor = 0xff000000";
_qlabel31.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 302;BA.debugLine="QLabel31.Gravity = Gravity.Left";
_qlabel31.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 303;BA.debugLine="QLabel31.Text = \"Cost(Php)\"";
_qlabel31.setText(BA.ObjectToCharSequence("Cost(Php)"));
 //BA.debugLineNum = 304;BA.debugLine="QLabel31.TextSize = 12";
_qlabel31.setTextSize((float) (12));
 //BA.debugLineNum = 305;BA.debugLine="QLabel31.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel31.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 306;BA.debugLine="mBase.AddView(QLabel31,0.51 * mBase.Width,0.57 *";
_mbase.AddView((android.view.View)(_qlabel31.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.57*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 308;BA.debugLine="cost2.Color =  0x00ffffff";
_cost2.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 309;BA.debugLine="cost2.TextColor = 0xff000000";
_cost2.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 310;BA.debugLine="cost2.Gravity = Gravity.Left";
_cost2.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 311;BA.debugLine="cost2.Text = \"Cost 2\"";
_cost2.setText(BA.ObjectToCharSequence("Cost 2"));
 //BA.debugLineNum = 312;BA.debugLine="mBase.AddView(cost2,0.69 * mBase.Width,0.57 * mBa";
_mbase.AddView((android.view.View)(_cost2.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.57*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 315;BA.debugLine="kwh3.Color =  0x00ffffff";
_kwh3.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 316;BA.debugLine="kwh3.TextColor = 0xff000000";
_kwh3.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 317;BA.debugLine="kwh3.Gravity = Gravity.Left";
_kwh3.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 318;BA.debugLine="kwh3.Text = \"kWh\"";
_kwh3.setText(BA.ObjectToCharSequence("kWh"));
 //BA.debugLineNum = 319;BA.debugLine="kwh3.TextSize = 14";
_kwh3.setTextSize((float) (14));
 //BA.debugLineNum = 320;BA.debugLine="kwh3.Typeface = sourcesanspro.DEFAULT_BOLD";
_kwh3.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 321;BA.debugLine="mBase.AddView(kwh3,0.14 * mBase.Width,0.77 * mBas";
_mbase.AddView((android.view.View)(_kwh3.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.77*_mbase.getHeight()),(int) (0.33*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 323;BA.debugLine="QLabel34.Color =  0x00ffffff";
_qlabel34.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 324;BA.debugLine="QLabel34.TextColor = 0xff000000";
_qlabel34.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 325;BA.debugLine="QLabel34.Gravity = Gravity.Left";
_qlabel34.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 326;BA.debugLine="QLabel34.Text = \"Current\"";
_qlabel34.setText(BA.ObjectToCharSequence("Current"));
 //BA.debugLineNum = 327;BA.debugLine="QLabel34.TextSize = 12";
_qlabel34.setTextSize((float) (12));
 //BA.debugLineNum = 328;BA.debugLine="QLabel34.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel34.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 329;BA.debugLine="mBase.AddView(QLabel34,0.14 * mBase.Width,0.82 *";
_mbase.AddView((android.view.View)(_qlabel34.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.82*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 331;BA.debugLine="current3.Color =  0x00ffffff";
_current3.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 332;BA.debugLine="current3.TextColor = 0xff000000";
_current3.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 333;BA.debugLine="current3.Gravity = Gravity.Left";
_current3.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 334;BA.debugLine="current3.Text = \"Current 3\"";
_current3.setText(BA.ObjectToCharSequence("Current 3"));
 //BA.debugLineNum = 335;BA.debugLine="mBase.AddView(current3,0.31 * mBase.Width,0.82 *";
_mbase.AddView((android.view.View)(_current3.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.82*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 337;BA.debugLine="QLabel36.Color =  0x00ffffff";
_qlabel36.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 338;BA.debugLine="QLabel36.TextColor = 0xff000000";
_qlabel36.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 339;BA.debugLine="QLabel36.Gravity = Gravity.Left";
_qlabel36.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 340;BA.debugLine="QLabel36.Text = \"Voltage\"";
_qlabel36.setText(BA.ObjectToCharSequence("Voltage"));
 //BA.debugLineNum = 341;BA.debugLine="QLabel36.TextSize = 12";
_qlabel36.setTextSize((float) (12));
 //BA.debugLineNum = 342;BA.debugLine="QLabel36.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel36.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 343;BA.debugLine="mBase.AddView(QLabel36,0.14 * mBase.Width,0.87 *";
_mbase.AddView((android.view.View)(_qlabel36.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.87*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 345;BA.debugLine="voltage3.Color =  0x00ffffff";
_voltage3.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 346;BA.debugLine="voltage3.TextColor = 0xff000000";
_voltage3.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 347;BA.debugLine="voltage3.Gravity = Gravity.Left";
_voltage3.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 348;BA.debugLine="voltage3.Text = \"Voltage 3\"";
_voltage3.setText(BA.ObjectToCharSequence("Voltage 3"));
 //BA.debugLineNum = 349;BA.debugLine="mBase.AddView(voltage3,0.31 * mBase.Width,0.87 *";
_mbase.AddView((android.view.View)(_voltage3.getObject()),(int) (0.31*_mbase.getWidth()),(int) (0.87*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 351;BA.debugLine="QLabel38.Color =  0x00ffffff";
_qlabel38.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 352;BA.debugLine="QLabel38.TextColor = 0xff000000";
_qlabel38.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 353;BA.debugLine="QLabel38.Gravity = Gravity.Left";
_qlabel38.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 354;BA.debugLine="QLabel38.Text = \"Power\"";
_qlabel38.setText(BA.ObjectToCharSequence("Power"));
 //BA.debugLineNum = 355;BA.debugLine="QLabel38.TextSize = 12";
_qlabel38.setTextSize((float) (12));
 //BA.debugLineNum = 356;BA.debugLine="QLabel38.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel38.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 357;BA.debugLine="mBase.AddView(QLabel38,0.51 * mBase.Width,0.82 *";
_mbase.AddView((android.view.View)(_qlabel38.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.82*_mbase.getHeight()),(int) (0.16*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 359;BA.debugLine="power3.Color =  0x00ffffff";
_power3.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 360;BA.debugLine="power3.TextColor = 0xff000000";
_power3.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 361;BA.debugLine="power3.Gravity = Gravity.Left";
_power3.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 362;BA.debugLine="power3.Text = \"Power 3\"";
_power3.setText(BA.ObjectToCharSequence("Power 3"));
 //BA.debugLineNum = 363;BA.debugLine="mBase.AddView(power3,0.69 * mBase.Width,0.82 * mB";
_mbase.AddView((android.view.View)(_power3.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.82*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 365;BA.debugLine="QLabel40.Color =  0x00ffffff";
_qlabel40.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 366;BA.debugLine="QLabel40.TextColor = 0xff000000";
_qlabel40.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 367;BA.debugLine="QLabel40.Gravity = Gravity.Left";
_qlabel40.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 368;BA.debugLine="QLabel40.Text = \"Cost(Php)\"";
_qlabel40.setText(BA.ObjectToCharSequence("Cost(Php)"));
 //BA.debugLineNum = 369;BA.debugLine="QLabel40.TextSize = 12";
_qlabel40.setTextSize((float) (12));
 //BA.debugLineNum = 370;BA.debugLine="QLabel40.Typeface = sourcesanspro.DEFAULT_BOLD";
_qlabel40.setTypeface(_sourcesanspro.DEFAULT_BOLD);
 //BA.debugLineNum = 371;BA.debugLine="mBase.AddView(QLabel40,0.51 * mBase.Width,0.87 *";
_mbase.AddView((android.view.View)(_qlabel40.getObject()),(int) (0.51*_mbase.getWidth()),(int) (0.87*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 373;BA.debugLine="cost3.Color =  0x00ffffff";
_cost3.setColor(((int)0x00ffffff));
 //BA.debugLineNum = 374;BA.debugLine="cost3.TextColor = 0xff000000";
_cost3.setTextColor(((int)0xff000000));
 //BA.debugLineNum = 375;BA.debugLine="cost3.Gravity = Gravity.Left";
_cost3.setGravity(__c.Gravity.LEFT);
 //BA.debugLineNum = 376;BA.debugLine="cost3.Text = \"Cost 3\"";
_cost3.setText(BA.ObjectToCharSequence("Cost 3"));
 //BA.debugLineNum = 377;BA.debugLine="mBase.AddView(cost3,0.69 * mBase.Width,0.87 * mBa";
_mbase.AddView((android.view.View)(_cost3.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.87*_mbase.getHeight()),(int) (0.19*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 379;BA.debugLine="mBase.AddView(btnback,0.06 * mBase.Width,0.03 * m";
_mbase.AddView((android.view.View)(_btnback.getObject()),(int) (0.06*_mbase.getWidth()),(int) (0.03*_mbase.getHeight()),(int) (0.09*_mbase.getWidth()),(int) (0.05*_mbase.getHeight()));
 //BA.debugLineNum = 380;BA.debugLine="mBase.AddView(on1,0.49 * mBase.Width,0.16 * mBase";
_mbase.AddView((android.view.View)(_on1.getObject()),(int) (0.49*_mbase.getWidth()),(int) (0.16*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 381;BA.debugLine="mBase.AddView(on3,0.49 * mBase.Width,0.73 * mBase";
_mbase.AddView((android.view.View)(_on3.getObject()),(int) (0.49*_mbase.getWidth()),(int) (0.73*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 382;BA.debugLine="mBase.AddView(on2,0.49 * mBase.Width,0.44 * mBase";
_mbase.AddView((android.view.View)(_on2.getObject()),(int) (0.49*_mbase.getWidth()),(int) (0.44*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 383;BA.debugLine="mBase.AddView(off1,0.69 * mBase.Width,0.16 * mBas";
_mbase.AddView((android.view.View)(_off1.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.16*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 384;BA.debugLine="mBase.AddView(off2,0.69 * mBase.Width,0.44 * mBas";
_mbase.AddView((android.view.View)(_off2.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.44*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 385;BA.debugLine="mBase.AddView(off3,0.69 * mBase.Width,0.73 * mBas";
_mbase.AddView((android.view.View)(_off3.getObject()),(int) (0.69*_mbase.getWidth()),(int) (0.73*_mbase.getHeight()),(int) (0.17*_mbase.getWidth()),(int) (0.06*_mbase.getHeight()));
 //BA.debugLineNum = 387;BA.debugLine="mBase.AddView(line1Title,0.14 * mBase.Width,0.16";
_mbase.AddView((android.view.View)(_line1title.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.16*_mbase.getHeight()),(int) (0.20*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 388;BA.debugLine="mBase.AddView(line2Title,0.14 * mBase.Width,0.44";
_mbase.AddView((android.view.View)(_line2title.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.44*_mbase.getHeight()),(int) (0.20*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 389;BA.debugLine="mBase.AddView(line3Title,0.14 * mBase.Width,0.73";
_mbase.AddView((android.view.View)(_line3title.getObject()),(int) (0.14*_mbase.getWidth()),(int) (0.73*_mbase.getHeight()),(int) (0.20*_mbase.getWidth()),(int) (0.04*_mbase.getHeight()));
 //BA.debugLineNum = 390;BA.debugLine="End Sub";
return "";
}
public String  _initialize(anywheresoftware.b4a.BA _ba,Object _callback,String _eventname) throws Exception{
innerInitialize(_ba);
 //BA.debugLineNum = 63;BA.debugLine="Public Sub Initialize (Callback As Object, EventNa";
 //BA.debugLineNum = 64;BA.debugLine="mEventName = EventName";
_meventname = _eventname;
 //BA.debugLineNum = 65;BA.debugLine="mCallBack = Callback";
_mcallback = _callback;
 //BA.debugLineNum = 66;BA.debugLine="bkgimage.Initialize(\"bkgimage\")";
_bkgimage.Initialize(ba,"bkgimage");
 //BA.debugLineNum = 67;BA.debugLine="QLabel1.Initialize(\"QLabel1\")";
_qlabel1.Initialize(ba,"QLabel1");
 //BA.debugLineNum = 68;BA.debugLine="btnback.Initialize(\"btnback\")";
_btnback.Initialize(ba,"btnback");
 //BA.debugLineNum = 69;BA.debugLine="on1.Initialize(\"on1\")";
_on1.Initialize(ba,"on1");
 //BA.debugLineNum = 70;BA.debugLine="on3.Initialize(\"on3\")";
_on3.Initialize(ba,"on3");
 //BA.debugLineNum = 71;BA.debugLine="on2.Initialize(\"on2\")";
_on2.Initialize(ba,"on2");
 //BA.debugLineNum = 72;BA.debugLine="off1.Initialize(\"off1\")";
_off1.Initialize(ba,"off1");
 //BA.debugLineNum = 73;BA.debugLine="off2.Initialize(\"off2\")";
_off2.Initialize(ba,"off2");
 //BA.debugLineNum = 74;BA.debugLine="off3.Initialize(\"off3\")";
_off3.Initialize(ba,"off3");
 //BA.debugLineNum = 75;BA.debugLine="realtimeTitle.Initialize(\"realtimeTitle\")";
_realtimetitle.Initialize(ba,"realtimeTitle");
 //BA.debugLineNum = 76;BA.debugLine="line2Title.Initialize(\"line2Title\")";
_line2title.Initialize(ba,"line2Title");
 //BA.debugLineNum = 77;BA.debugLine="line1Title.Initialize(\"line1Title\")";
_line1title.Initialize(ba,"line1Title");
 //BA.debugLineNum = 78;BA.debugLine="line3Title.Initialize(\"line3Title\")";
_line3title.Initialize(ba,"line3Title");
 //BA.debugLineNum = 79;BA.debugLine="kwh1.Initialize(\"kwh1\")";
_kwh1.Initialize(ba,"kwh1");
 //BA.debugLineNum = 80;BA.debugLine="QLabel18.Initialize(\"QLabel18\")";
_qlabel18.Initialize(ba,"QLabel18");
 //BA.debugLineNum = 81;BA.debugLine="QLabel17.Initialize(\"QLabel17\")";
_qlabel17.Initialize(ba,"QLabel17");
 //BA.debugLineNum = 82;BA.debugLine="power1.Initialize(\"power1\")";
_power1.Initialize(ba,"power1");
 //BA.debugLineNum = 83;BA.debugLine="voltage1.Initialize(\"voltage1\")";
_voltage1.Initialize(ba,"voltage1");
 //BA.debugLineNum = 84;BA.debugLine="QLabel20.Initialize(\"QLabel20\")";
_qlabel20.Initialize(ba,"QLabel20");
 //BA.debugLineNum = 85;BA.debugLine="current1.Initialize(\"current1\")";
_current1.Initialize(ba,"current1");
 //BA.debugLineNum = 86;BA.debugLine="QLabel22.Initialize(\"QLabel22\")";
_qlabel22.Initialize(ba,"QLabel22");
 //BA.debugLineNum = 87;BA.debugLine="cost1.Initialize(\"cost1\")";
_cost1.Initialize(ba,"cost1");
 //BA.debugLineNum = 88;BA.debugLine="kwh2.Initialize(\"kwh2\")";
_kwh2.Initialize(ba,"kwh2");
 //BA.debugLineNum = 89;BA.debugLine="QLabel25.Initialize(\"QLabel25\")";
_qlabel25.Initialize(ba,"QLabel25");
 //BA.debugLineNum = 90;BA.debugLine="current2.Initialize(\"current2\")";
_current2.Initialize(ba,"current2");
 //BA.debugLineNum = 91;BA.debugLine="QLabel27.Initialize(\"QLabel27\")";
_qlabel27.Initialize(ba,"QLabel27");
 //BA.debugLineNum = 92;BA.debugLine="voltage2.Initialize(\"voltage2\")";
_voltage2.Initialize(ba,"voltage2");
 //BA.debugLineNum = 93;BA.debugLine="QLabel29.Initialize(\"QLabel29\")";
_qlabel29.Initialize(ba,"QLabel29");
 //BA.debugLineNum = 94;BA.debugLine="power2.Initialize(\"power2\")";
_power2.Initialize(ba,"power2");
 //BA.debugLineNum = 95;BA.debugLine="QLabel31.Initialize(\"QLabel31\")";
_qlabel31.Initialize(ba,"QLabel31");
 //BA.debugLineNum = 96;BA.debugLine="cost2.Initialize(\"cost2\")";
_cost2.Initialize(ba,"cost2");
 //BA.debugLineNum = 97;BA.debugLine="kwh3.Initialize(\"kwh3\")";
_kwh3.Initialize(ba,"kwh3");
 //BA.debugLineNum = 98;BA.debugLine="QLabel34.Initialize(\"QLabel34\")";
_qlabel34.Initialize(ba,"QLabel34");
 //BA.debugLineNum = 99;BA.debugLine="current3.Initialize(\"current3\")";
_current3.Initialize(ba,"current3");
 //BA.debugLineNum = 100;BA.debugLine="QLabel36.Initialize(\"QLabel36\")";
_qlabel36.Initialize(ba,"QLabel36");
 //BA.debugLineNum = 101;BA.debugLine="voltage3.Initialize(\"voltage3\")";
_voltage3.Initialize(ba,"voltage3");
 //BA.debugLineNum = 102;BA.debugLine="QLabel38.Initialize(\"QLabel38\")";
_qlabel38.Initialize(ba,"QLabel38");
 //BA.debugLineNum = 103;BA.debugLine="power3.Initialize(\"power3\")";
_power3.Initialize(ba,"power3");
 //BA.debugLineNum = 104;BA.debugLine="QLabel40.Initialize(\"QLabel40\")";
_qlabel40.Initialize(ba,"QLabel40");
 //BA.debugLineNum = 105;BA.debugLine="cost3.Initialize(\"cost3\")";
_cost3.Initialize(ba,"cost3");
 //BA.debugLineNum = 106;BA.debugLine="End Sub";
return "";
}
public String  _off1_click() throws Exception{
 //BA.debugLineNum = 428;BA.debugLine="Sub off1_click()";
 //BA.debugLineNum = 429;BA.debugLine="Starter.wsh.SendClient(\"SSROFF1#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSROFF1#");
 //BA.debugLineNum = 430;BA.debugLine="saveline(1,\"OFF\",Starter.enKW1)";
_saveline(BA.NumberToString(1),"OFF",_starter._enkw1 /*String*/ );
 //BA.debugLineNum = 431;BA.debugLine="ToastMessageShow(\"LINE 1 OFF\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 1 OFF"),__c.False);
 //BA.debugLineNum = 432;BA.debugLine="End Sub";
return "";
}
public String  _off2_click() throws Exception{
 //BA.debugLineNum = 433;BA.debugLine="Sub off2_click()";
 //BA.debugLineNum = 434;BA.debugLine="Starter.wsh.SendClient(\"SSROFF2#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSROFF2#");
 //BA.debugLineNum = 435;BA.debugLine="saveline(2,\"OFF\",Starter.enKW2)";
_saveline(BA.NumberToString(2),"OFF",_starter._enkw2 /*String*/ );
 //BA.debugLineNum = 436;BA.debugLine="ToastMessageShow(\"LINE 2 OFF\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 2 OFF"),__c.False);
 //BA.debugLineNum = 437;BA.debugLine="End Sub";
return "";
}
public String  _off3_click() throws Exception{
 //BA.debugLineNum = 438;BA.debugLine="Sub off3_click()";
 //BA.debugLineNum = 439;BA.debugLine="Starter.wsh.SendClient(\"SSROFF3#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSROFF3#");
 //BA.debugLineNum = 440;BA.debugLine="saveline(3,\"OFF\",Starter.enKW3)";
_saveline(BA.NumberToString(3),"OFF",_starter._enkw3 /*String*/ );
 //BA.debugLineNum = 441;BA.debugLine="ToastMessageShow(\"LINE 3 OFF\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 3 OFF"),__c.False);
 //BA.debugLineNum = 442;BA.debugLine="End Sub";
return "";
}
public String  _on1_click() throws Exception{
 //BA.debugLineNum = 406;BA.debugLine="Sub on1_click()";
 //BA.debugLineNum = 407;BA.debugLine="Starter.wsh.SendClient(\"SSRON1#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSRON1#");
 //BA.debugLineNum = 408;BA.debugLine="saveline(1,\"ON\",Starter.enKW1)";
_saveline(BA.NumberToString(1),"ON",_starter._enkw1 /*String*/ );
 //BA.debugLineNum = 409;BA.debugLine="ToastMessageShow(\"LINE 1 ON\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 1 ON"),__c.False);
 //BA.debugLineNum = 410;BA.debugLine="End Sub";
return "";
}
public String  _on2_click() throws Exception{
 //BA.debugLineNum = 418;BA.debugLine="Sub on2_click()";
 //BA.debugLineNum = 419;BA.debugLine="Starter.wsh.SendClient(\"SSRON2#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSRON2#");
 //BA.debugLineNum = 420;BA.debugLine="saveline(2,\"ON\",Starter.enKW2)";
_saveline(BA.NumberToString(2),"ON",_starter._enkw2 /*String*/ );
 //BA.debugLineNum = 421;BA.debugLine="ToastMessageShow(\"LINE 2 ON\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 2 ON"),__c.False);
 //BA.debugLineNum = 422;BA.debugLine="End Sub";
return "";
}
public String  _on3_click() throws Exception{
 //BA.debugLineNum = 423;BA.debugLine="Sub on3_click()";
 //BA.debugLineNum = 424;BA.debugLine="Starter.wsh.SendClient(\"SSRON3#\")";
_starter._wsh /*b4a.esalbaapp.wtaserver*/ ._sendclient /*String*/ ("SSRON3#");
 //BA.debugLineNum = 425;BA.debugLine="saveline(3,\"ON\",Starter.enKW3)";
_saveline(BA.NumberToString(3),"ON",_starter._enkw3 /*String*/ );
 //BA.debugLineNum = 426;BA.debugLine="ToastMessageShow(\"LINE 3 ON\", False)";
__c.ToastMessageShow(BA.ObjectToCharSequence("LINE 3 ON"),__c.False);
 //BA.debugLineNum = 427;BA.debugLine="End Sub";
return "";
}
public void  _saveline(String _line,String _state,String _kw) throws Exception{
ResumableSub_saveline rsub = new ResumableSub_saveline(this,_line,_state,_kw);
rsub.resume(ba, null);
}
public static class ResumableSub_saveline extends BA.ResumableSub {
public ResumableSub_saveline(b4a.esalbaapp.frmcontrol parent,String _line,String _state,String _kw) {
this.parent = parent;
this._line = _line;
this._state = _state;
this._kw = _kw;
}
b4a.esalbaapp.frmcontrol parent;
String _line;
String _state;
String _kw;
b4a.esalbaapp.clswidget _cc = null;
String _sql = "";
anywheresoftware.b4a.keywords.Common.ResumableSubWrapper _rs = null;
anywheresoftware.b4a.objects.collections.List _l = null;

@Override
public void resume(BA ba, Object[] result) throws Exception{

    while (true) {
        switch (state) {
            case -1:
return;

case 0:
//C
this.state = -1;
 //BA.debugLineNum = 412;BA.debugLine="Dim cc As clswidget";
_cc = new b4a.esalbaapp.clswidget();
 //BA.debugLineNum = 413;BA.debugLine="cc.Initialize(Me)";
_cc._initialize /*String*/ (ba,(anywheresoftware.b4a.objects.B4XViewWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.B4XViewWrapper(), (java.lang.Object)(parent)));
 //BA.debugLineNum = 414;BA.debugLine="Dim sql As String=$\"insert into history(Line,Stat";
_sql = ("insert into history(Line,State,KW,Date) values ('"+parent.__c.SmartStringFormatter("",(Object)(_line))+"','"+parent.__c.SmartStringFormatter("",(Object)(_state))+"','"+parent.__c.SmartStringFormatter("",(Object)(_kw))+"','"+parent.__c.SmartStringFormatter("",(Object)(parent._starter._wsh /*b4a.esalbaapp.wtaserver*/ ._datetimesql /*String*/ ()))+"')");
 //BA.debugLineNum = 415;BA.debugLine="Dim rs As ResumableSub = cc.Querry(sql,\"QUERRY\")";
_rs = new anywheresoftware.b4a.keywords.Common.ResumableSubWrapper();
_rs = _cc._querry /*anywheresoftware.b4a.keywords.Common.ResumableSubWrapper*/ (_sql,"QUERRY");
 //BA.debugLineNum = 416;BA.debugLine="Wait For(rs) Complete (l As List)";
parent.__c.WaitFor("complete", ba, this, _rs);
this.state = 1;
return;
case 1:
//C
this.state = -1;
_l = (anywheresoftware.b4a.objects.collections.List) result[0];
;
 //BA.debugLineNum = 417;BA.debugLine="End Sub";
if (true) break;

            }
        }
    }
}
public void  _complete(anywheresoftware.b4a.objects.collections.List _l) throws Exception{
}
public String  _seat2_click() throws Exception{
 //BA.debugLineNum = 401;BA.debugLine="Sub seat2_click()";
 //BA.debugLineNum = 402;BA.debugLine="End Sub";
return "";
}
public String  _setlayout(int _left,int _top,int _width,int _height) throws Exception{
 //BA.debugLineNum = 450;BA.debugLine="Public Sub SetLayout(Left As Int,Top As Int,Width";
 //BA.debugLineNum = 451;BA.debugLine="mBase.SetLayout(Left,Top,Width,Height )";
_mbase.SetLayout(_left,_top,_width,_height);
 //BA.debugLineNum = 452;BA.debugLine="End Sub";
return "";
}
public String  _setvisible(boolean _flag) throws Exception{
 //BA.debugLineNum = 447;BA.debugLine="Public Sub setVisible(flag As Boolean)";
 //BA.debugLineNum = 448;BA.debugLine="mBase.Visible=flag";
_mbase.setVisible(_flag);
 //BA.debugLineNum = 449;BA.debugLine="End Sub";
return "";
}
public Object callSub(String sub, Object sender, Object[] args) throws Exception {
BA.senderHolder.set(sender);
return BA.SubDelegator.SubNotFound;
}
}
